# Ansible galaxy requirements for fetching all role dependencies that are not
# registered on galaxy.ansible.com.
---
- src: https://github.com/drunomics/ansible-role-java
  name: drunomics.java

# Use our fork for ansible 2.2. compatibility.
- src: git@github.com:drunomics/ansible-elasticsearch.git
  name: gpstathis.elasticsearch
